FROM docker.io/hexpm/elixir:1.18.3-erlang-27.3.4-debian-bookworm-20250428-slim

RUN apt-get update && apt-get install -y build-essential git npm inotify-tools && rm -rf /var/lib/apt/lists/*

WORKDIR /app/ex_cellence_server

ENV MIX_ENV=dev

RUN mix local.hex --force && mix local.rebar --force

EXPOSE 4001

CMD ["sh", "-c", "mix deps.get && mix ecto.migrate && mix phx.server"]
